version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: poetry
      path: .
      extras: []   # optional: you could include ["plotting"] if docs need matplotlib

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false